openapi: 3.0.1
info: 
  title: Entitlement Management
  description: |
    This interface provides access to the **Entitlement Management** of a personal health 
    record for the ombuds office.<br/> 
    
    **General conditions**:</br> 
    For all operations if applicable:
    - a section _Client_ in operation descriptions covers recommendations (informative) for clients.
    - a section _Provider_ in operation descriptions covers requirements for the server side. 
    - error responses may be extended by helpful information about the error condition in _errorDetail_

    **Prereqisites**:</br>
    The Health Record System shall provide 
    - name
    - role ((profession-)oid)
    - identifier (telematik-id or kvnr)
    - indication of a valid entitlement 
    
    of the current user (requestor) for evaluation in operations.

    Operations mandating a valid entitlement implicitely mandate use of a VAU-channel
    and a valid ID-Token. If one of these conditions is not met, then the response
    of the (aborted) operation shall always be '403': 'notEntitled'. 

    **Retry interval**:</br>
    The following retry intervals are suggested in case of an error response:<br>
    - '409' Conflict (statusMismatch).
      - approx. 24 hours
    - '500' Internal Error
      - approx. 10 minutes

    **User Agent**:</br>
    The user agent information (x-useragent) is part of any request, even if 
    not essentially required for the operation (e.g. raw-data collection), and
    may be considered for provider internal use. 

    **Log-Entries**
    Whenever a _Postcondition_ mandates a log-entry, this entry shall contain
    data as defined in A_24928*.

  contact:
    name: gematik GmbH
    email: epa@gematik.de
    url: 'http://www.gematik.de'

  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

  version: 0.0.1
  
  # version history:
  # ----------------
  # version 0.0.1
  #   - initial version for review

servers:
  - url: 'https://example.com/api'

tags:
  - name: UserBlocking
    description: |
      User blocking allows configuration of the blocked user policy of a health record for the 
      entitled ombuds office by setting or deleting assignments.</br>
      An assignment is related to a single user identified by a telematik-id. Any user covered by 
      an assignment is excluded from entitlement, i.e. can not be entitled and existing entitlements are 
      deleted.
      
      **Allowed usergroups for user blocking:**:</br> 
      The blocked user policy shall have entries for users of the following roles (professionOid) only.</br>
      The following list of oids is for information only and may be incomplete, the normative requirement is defined in A_24463-*
      - oid_praxis_arzt
      - oid_krankenhaus
      - oid_institution-vorsorge-reha
      - oid_zahnarztpraxis
      - oid_Ã¶ffentliche_apotheke
      - oid_praxis_psychotherapeut
      - oid_institution-pflege
      - oid_institution-geburtshilfe
      - oid_praxis-physiotherapeut
      - oid_institution-oegd
      - oid_institution-arbeitsmedizin

  - name: Selfdisclosure
    description: Information about this API
     
paths:
  /entitlementmanagement/blockeduser:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/useragent'      
    get:
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/telematikid'
        - $ref: '#/components/parameters/oid'
      tags:
        - UserBlocking
      operationId: getBlockedUserPolicyAssignmentsOmbud
      summary: (getBlockedUserPolicyAssignmentsOmbud) Get a list of blocked users
      description: |
        Get a list of actual set assignments of the blocked user policy.</br>
        This operation is limited to entitled users of role oid_ombudsstelle.

        **Client**:</br>
        A client shall consider the schema for 'Queries' and 'Paging' (see below).

        **Provider**:</br>
        The returned list shall contain only assignments of the blocked user policy matching the query parameters.</br>
        Different query parameter (name) shall be applied as logical AND, multiple query strings (same name) 
        as OR. Default for all query parameters is ('*').

        Paging:</br>
        _offset_ and _limit_ parameters shall be related to the amount of assignments matching the query. 
        Default shall be for _offset_ = 0 and for _limit_ = 50 (this shall also be the maximum _limit_).
        The applied _offset_ and _limit_ and the total amount of matching assignments shall be part of the response.</br>
        _offset_ shall be a "page-offset" and is related to _limit_ which is the "page-size", e.g. if total amount of 
        matching assignments is 75, than _offset_ = 0 with _limit_ = 40 return result 1 to 40 and _offset_ = 1 with _limit_ 
        = 40 return result 41 to 75 and _offset_ = 2 with _limit_ = 40 return an 'empty' result.  
        
        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_ombudsstelle_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | none ||

      responses:
        '200':
          description: Ok. Returns a list of policy assignments
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: object
                    properties:
                      offset:
                        description: applied offset to matching results
                        type: integer
                      limit: 
                        description: applied limit to matching results
                        type: integer
                      totalMatching:
                        description: total amount of matching results in policy
                        type: integer
                  assignments:
                    type: array
                    items:
                      allOf:
                      - $ref: '#/components/schemas/BlockedUserPolicyAssignmentResponseType'
              examples:
                getAll:
                  $ref: '#/components/examples/Get_AllPolicyAssignments'
                getAllOffsetLimit:
                  $ref: '#/components/examples/Get_AllPolicyAssignments_offset_limit'
                FilterTID:
                  $ref: '#/components/examples/Get_QueryForTID'
                FilterOid:
                  $ref: '#/components/examples/Get_QueryForRole'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

    post:
      tags:
        - UserBlocking
      operationId: setBlockedUserPolicyAssignmentOmbud
      summary: (setBlockedUserPolicyAssignmentOmbud) Add a user to the blocked user policy
      description: |
        Set a new assignment for the blocked user policy.</br>
        The user addressed by the policy assignment can not be entitled by any means, a possibly existing 
        entitlement is lost.</br>
        This operation is limited to entitled users of role oid_ombudsstelle.

        **Client**:</br>
        A client of the ombuds office shall set assigments for users of the allowed roles for 
        user blocking only.</br>

        **Provider**:</br>
        A valid new assignment shall be added to the blocked user policy.

        Each new valid assigment shall be extended by a timestamp (_at_ = current date and time)
        by the server.

        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_ombudsstelle_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | The assignment parameter _oid_ is not in the list of allowd oids | 409 | requestMismatch ||
        | The assignment does yet exist (same _actorId_) | 409 | requestMismatch | avoid duplicates |
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | The policy assignment is extended with the timestamp and stored in SecureDataStorage ||
        | An existing entitlement for the addressed user of the assignment is deleted ||
        | A log-entry for the operation exists | all operation results |

      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/BlockedUserPolicyAssignmentType'
            examples:
              onePolicy:
                $ref: '#/components/examples/Set_SinglePolicyAssignment'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/BlockedUserPolicyAssignmentResponseType'
              examples:
                onePolicy:
                  $ref: '#/components/examples/Get_SinglePolicyAssignment'

        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

  /entitlementmanagement/blockeduser/{actorId}:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/actorId'
      - $ref: '#/components/parameters/useragent'      
    delete:
      tags:
        - UserBlocking
      operationId: deleteBlockedUserPolicyAssignmentOmbud
      summary: (deleteBlockedUserPolicyAssignmentOmbud) Remove a user from the blocked user policy
      description: |
        Delete one existing assignment of the blocked user policy.</br>
        This operation is limited to entitled users of role oid_ombudsstelle.

        **Client**:</br>
        no recommendations.

        **Provider**:</br>
        The addressed assigment shall be removed from the policy.

        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 204 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_ombudsstelle_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Assignment (_assignmentid_) does not exist | 404 | noResource ||
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | The addressed assignment is removed from the associated policy ||
        | A log-entry for the operation exists | all operation results |

      responses:
        '204':
          description: OK. Assignment deleted
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

  /:
    get:
      tags:
        - Selfdisclosure
      operationId: getInfo
      summary: Get API information
      description: (getInfo) Returns the meta data of this interface.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoObject"
        '500':
          description: Internal Server Error

components:
  responses:
    Error400BadRequest:
      description: Bad Request.
      content:
        application/json:
          example:
            errorCode: malformedRequest
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error401Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          example:
            errorCode: invalSignature
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error403Forbidden:
      description: Forbidden.
      content:
        application/json:
          example:
            errorCode: notEntitled
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error404NotFound:
      description: Not found.
      content:
        application/json:
          example:
            errorCode: noResource
            errorDetail: Identifier of requested resource
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error409Conflict:
      description: Conflict.
      content:
        application/json:
          examples:
            statusMismatch:
              value:
                errorCode: statusMismatch
                errorDetail: SUSPENDED
            requestMismatch:
              value:
                errorCode: requestMismatch
                errorDetail: 1.2.276.0.76.4.273
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error500InternalError:
      description: Internal Server Error
      content:
        application/json:
          example:
            errorCode: internalError
            errorDetail: additional information if applicable
          schema:
            $ref: '#/components/schemas/ErrorType'

  parameters:
    insurantid:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: '#/components/schemas/InsurantIdType'
    useragent:
      name: x-useragent
      in: header
      description: user agent information
      required: true
      schema:
        $ref: '#/components/schemas/UserAgentType'
    actorId:
      name: actorId
      in: path
      description: TelematikID
      required: true
      schema:
        $ref: '#/components/schemas/TelematikIdType'

  schemas:
    TelematikIdType:
      type: string
      pattern: '[0-9]{1}[-]{1}\d{1,126}$'
      example: 2-883110000118994
    OidType:
      description: A professionOID
      type: string
      pattern: '([0-2])((\.0)|(\.[1-9][0-9]*))*$'
      example: '1.2.276.0.76.4.50'
    DisplayNameType:
      description: A readable name
      type: string
      example: 'Praxis Dr. Annamaria HeckhausÃ©n'
    BlockedUserPolicyAssignmentType:
      description: Properties of one specific user
      type: object
      required:
        - actorId
        - oid
        - displayName
      properties:
        actorId:
          $ref: '#/components/schemas/TelematikIdType'
        oid:
          $ref: '#/components/schemas/OidType'
        displayName:
          $ref: '#/components/schemas/DisplayNameType'
    BlockedUserPolicyAssignmentResponseType:
      allOf:
        - $ref: '#/components/schemas/BlockedUserPolicyAssignmentType'
        - type: object 
          properties:  
            at:
              description: Creation time timestamp 
              type: string
              format: date-time
              example: 2025-01-01T18:00:00Z
    UserAgentType:
      description: Information about client software.
      type: object
      properties:
        clientId:
          type: string
          pattern: '^[a-zA-Z0-9]{20}$'
        version:
          type: string
          pattern: '^[a-zA-Z0-9\-\.]{1,15}$'
      required:
        - clientId
        - version
      additionalProperties: false
    InsurantIdType:
      type: string
      description: |-
        The health record identifier. 
        For today the record identifier equals the insurant id (kvnr).
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    ErrorType:
      description: Error object with additional information about the occurred error
      type: object
      properties:
        errorCode:
          description: Error condition specifier
          type: string
        errorDetail:
          description: Additional details regarding the error condition (if applicable)
          type: string
      required:
        - errorCode
    InfoObject:
      description: "Self-disclosure of this interface"
      required:
        - title
        - version
      readOnly: true
      type: object
      properties:
        title:
          type: string
          description: "Title of the application"
          example: "Entitlement Management for the ombuds office"
        description:
          type: string
          description: "Short description of the application"
          example: "This interface provides operations for clients an entitled ombuds office
           to modify blocked user policy assignments."
        contact:
          type: string
          description: "Contact information"
          example: "kontakt@<Betreibername>"
        version:
          type: string
          description: "Interface version"
          example: "1.0.0"

  examples:
    Get_AllPolicyAssignments:
      summary: Get all Blocked User Policy assignments.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 4
        assignments:
          - actorId: 2-883110000092414
            oid: 1.2.276.0.76.4.51
            displayName: 'Zahnarztpraxis Norbert Freiherr Schomaker'
            at: 2025-07-01T12:00:00Z
          - actorId: 1-883110000092404
            oid: 1.2.276.0.76.4.50
            displayName: 'Praxis Dr. Annamaria HeckhausÃ©n'
            at: 2025-07-02T12:00:00Z
          - actorId: 2-883110000092427
            oid: 1.2.276.0.76.4.51
            displayName: 'Zahnarztpraxis Dr. Alfons AdamiÃ§'
            at: 2025-07-03T12:00:00Z
          - actorId: 3-883110000092469
            oid: 1.2.276.0.76.4.54
            displayName: 'SÃ¼d Apotheke'
            at: 2025-07-04T12:00:00Z
    Get_AllPolicyAssignments_offset_limit:
      summary: Get all Blocked User Policy assignments with set offset and limit.
      value:
        query: 
          offset: 1
          limit: 2
          totalMatching: 4
        assignments:
          - actorId: 2-883110000092427
            oid: 1.2.276.0.76.4.51
            displayName: 'Zahnarztpraxis Dr. Alfons AdamiÃ§'
            at: 2025-07-03T12:00:00Z
          - actorId: 3-883110000092469
            oid: 1.2.276.0.76.4.54
            displayName: 'SÃ¼d Apotheke'
            at: 2025-07-04T12:00:00Z
    Get_QueryForTID:
      summary: Get Blocked User Policy assignment for telematik-id 1-883110000092404.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 1
        assignments:
          - actorId: 1-883110000092404
            oid: 1.2.276.0.76.4.50
            displayName: 'Praxis Dr. Annamaria HeckhausÃ©n'
            at: 2025-07-02T12:00:00Z
    Get_QueryForRole:
      summary: Get Blocked User Policy assignment for oid oid_zahnarztpraxis.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 2
        assignments:
          - actorId: 2-883110000092414
            oid: 1.2.276.0.76.4.51
            displayName: 'Zahnarztpraxis Norbert Freiherr Schomaker'
            at: 2025-07-01T12:00:00Z
          - actorId: 2-883110000092427
            oid: 1.2.276.0.76.4.51
            displayName: 'Zahnarztpraxis Dr. Alfons AdamiÃ§'
            at: 2025-07-03T12:00:00Z
    Set_SinglePolicyAssignment: 
      summary: Set Blocked User Policy assignment for 2-883110000092427.
      value:
        actorId: 2-883110000092427
        oid: 1.2.276.0.76.4.51
        displayName: 'Zahnarztpraxis Dr. Alfons AdamiÃ§'
    Get_SinglePolicyAssignment:
      summary: Get Blocked User Policy assignment for 2-883110000092427.
      value:
        actorId: 2-883110000092427
        oid: 1.2.276.0.76.4.51
        displayName: 'Zahnarztpraxis Dr. Alfons AdamiÃ§'
        at: 2025-07-03T12:00:00Z
